# Default values for thanos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



global:
  imageRegistry: "docker.io"

# image:
#   registry: "docker.io"
#   repository: "bitnami/thanos"
#   tag: "0.27.0-scratch-r6"


commonLabels: {tribe: "dan", doman: "my_domain"}

commonAnnotations: {anotribe: "dan", anodomain: "my_ano_domain", anosquad: "dan_squad_ano"}

# query:
#   replicaCount: 3
  # extraEnvVars:
  #   - name: AWS_ACCESS_KEY
  #     value: AWS_ACCESS_KEY
  #   - name: AWS_SECRET_KEY
  #     value: AWS_SECRET_KEY

# queryFrontend:
#   replicaCount: 4
  # extraEnvVars:
  #   - name: AWS_ACCESS_KEY
  #     value: AWS_ACCESS_KEY
  #   - name: AWS_SECRET_KEY
  #     value: AWS_SECRET_KEY

objstoreConfig: |-
  type: S3
  config:
    bucket: "thanos-test-bucket"
    endpoint: "s3.eu-west-2.amazonaws.com"
    region: "eu-west-2"
    aws_sdk_auth: false
    access_key: AWS_ACCESS_KEY
    insecure: false
    signature_version2: false
    secret_key: AWS_SECRET_KEY
    # http_config:
    #   idle_conn_timeout: 90s
    #   response_header_timeout: 2m
    #   insecure_skip_verify: true


# bucketweb:
#   enabled: true
# compactor:
#   enabled: true
# storegateway:
#   enabled: true